baseURL = "https://irmoodie.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "The Personal Website of Iain R. Moodie"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Iain R. Moodie"
author = "I.R. Moodie"
description = "Master's student studying Evolutionary Biology."
uniCurrent = "Uppsala University, Sweden."
profilePicture = "images/profile.jpg"
#photoCredit = "Declan Caveney"
#photoCrediturl = "https://deccav.com"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
doNotLoadAnimations = true
images = []

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/irmoodie"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/irmoodie"


## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

#  [[menu.main]]
#  name = "About"
#  weight = 200
#  identifier = "about"
#  url = "/about/"
  
  [[menu.main]]
  name = "Research Interests"
  weight = 200
  identifier = "research"
  url = "/research/"
  
  [[menu.main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"
  
  [[menu.main]]
  name = "CV"
  weight = 400
  identifier = "cv"
  url = "/irmoodiecv.pdf/"
  
  [[menu.main]]
  name = "Blog Posts"
  weight = 500
  identifier = "posts"
  url = "/post/"